name: dummy
dir: src/github.com/jaekwonpark/gittest

environment:
  GOCLIENT: 

container:
  - base:
      - 192.168.106.181/build/aerospike-server:centos-6
      - 192.168.106.181/build/aerospike-server:centos-7

build:
  - name: hello
    environment:
      GREETING: hello
    script:
      - "echo $GREETING"
    artifact:
      - /etc/hosts
      - /work/source/src/github.com/jaekwonpark/gittest/README.md
