openapi: 3.0.1
info:
  title: This is the files AP definitions
  version: 1.0.0-SNAPSHOT
paths: {}
components:
  schemas:
    files.v4.r0.a1.file_servers.FileServer:
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.ExternalizableAbstractModel'
      - type: object
        properties:
          config:
            $ref: '#/components/schemas/files.v4.r0.a1.file_servers.FileServerConfig'
    files.v4.r0.a1.file_servers.Network:
      title: FileServer Config.
      description: FileServer config.
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.AbstractModel'
      - type: object
        properties:
          uuid:
            type: string
            description: Uuid of the network.
          name:
            type: string
            description: Name of the network.
          networkAddress:
            type: string
            description: NetworkAddress of the network.
          internalVirtualNetworkUuid:
            type: string
            description: Uuid of the internal network.
          externalVirtualNetworkUuid:
            type: string
            description: Uuid of the external network.
          isInternalNetwork:
            type: boolean
            description: Uuid of the external network.
          subnetMask:
            type: string
            description: Subnetmask of the network.
          defaultGateway:
            type: string
            description: Default Gateway of the network.
    files.v4.r0.a1.file_servers.FileServerConfig:
      title: FileServer Config.
      description: FileServer config.
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.AbstractModel'
      - type: object
        properties:
          uuid:
            type: string
            description: Uuid of the file server.
          name:
            type: string
            description: Name of the file server.
          description:
            type: string
            description: Description of the file server.
          dnsDomainNme:
            type: string
            description: Dns domain name of the file server.
          continerUuid:
            type: string
            description: Container uuid associated with file server.
          dnsServerIpAddresses:
            type: array
            description: Dns server ip addresses.
            items:
              type: string
          ntpServers:
            type: array
            description: ntp server ip addresses.
            items:
              type: string
          internalVirtualNetworkUuid:
            type: string
            description: ntp server ip addresses.
          externalVirtualNetworkUuids:
            type: array
            description: External network uuids.
            items:
              type: string
          internalNetwork:
            $ref: '#/components/schemas/files.v4.r0.a1.file_servers.Network'
          externalNetworks:
            type: array
            items:
              $ref: '#/components/schemas/files.v4.r0.a1.file_servers.Network'
          numShares:
            type: integer
            description: Num of shares associated with the file server
            format: int32
          numHomeShares:
            type: integer
            description: Num of home shares associated with file server.
            format: int32
          numNestedShares:
            type: integer
            description: Num of nested shares associated with file server.
            format: int32
          externalIpAddresses:
            type: array
            description: External ip addresses
            items:
              type: string
          version:
            type: string
            description: version of file server
          upgrdeInProgress:
            type: boolean
            description: Upgrade in progress flag
          protectedDomainState:
            type: boolean
            description: Protection domain Status
          pdStatus:
            type: boolean
            description: Pd Status
          protectionDomainName:
            type: string
            description: protectionDomainName
    common.unversioned.a1.data.types.ExternalizableAbstractModel:
      description: |
        An abstract representation of an object that is externally consumable via an API endpoint.
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.MetadataAbstractModel'
      - type: object
        properties:
          extId:
            type: string
            description: An identifier for the object that is suitable for external
              consumption.
          name:
            type: string
            description: |
              The tenant to which this object instance belongs.  Every Nutanix object belongs to a tenant. Once an object is created its tenancy cannot be changed.
          description:
            type: string
            description: |
              The tenant to which this object instance belongs.  Every Nutanix object belongs to a tenant. Once an object is created its tenancy cannot be changed.
          displayName:
            type: string
    common.unversioned.a1.data.types.MetadataAbstractModel:
      description: |
        An abstract representation of an object that is itself not consumable via an external API endpoint but provides metadata information in the form of HATEOAS links to the consumer.
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.AbstractModel'
      - type: object
        properties:
          links:
            type: array
            description: The HATEOAS links for the Vm API.  Minimally contains the
              self link
            items:
              $ref: '#/components/schemas/common.v5.r0.a1.response.types.ApiLink'
    common.unversioned.a1.data.types.AbstractModel:
      type: object
      properties:
        objectType:
          type: string
          description: A fully qualified name of the object represented by this entity
          readOnly: true
        tenantId:
          type: string
          description: |
            The tenant to which this object instance belongs.  Every Nutanix object belongs to a tenant. Once an object is created its tenancy cannot be changed.
          readOnly: true
