openapi: 3.0.1
info:
  title: This is the files AP definitions
  version: 1.0.0-SNAPSHOT
paths: {}
components:
  schemas:
    common.unversioned.a1.api.info.Namespace:
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.CategoryAwareModel'
      - type: object
        properties:
          name:
            type: string
            description: The name of this namespace
          version:
            type: string
            description: The string representation of the version this namespace belongs
              to
          endpoints:
            type: array
            description: The fully qualified endpoints defined in this (namespace,
              version, revision)
            items:
              type: string
          models:
            type: array
            description: The fully qualified model names defined in this (namespace,
              version, revision)
            items:
              type: string
          modelDependencies:
            type: array
            description: The other model endpoints that APIs in this (namespace, version,
              revision) depend on
            items:
              type: string
          versionType:
            $ref: '#/components/schemas/common.unversioned.a1.api.info.VersionType'
    common.unversioned.a1.api.info.VersionType:
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.BaseEnum'
      - type: string
        enum:
        - ALPHA
        - BETA
        - RELEASED
    common.unversioned.a1.data.types.CategoryAwareModel:
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.ExternalizableAbstractModel'
      - type: object
        properties:
          categories:
            type: array
            description: An identifier for the object that is suitable for external
              consumption.
            items:
              $ref: '#/components/schemas/common.unversioned.a1.data.types.Category'
    common.unversioned.a1.data.types.ExternalizableAbstractModel:
      description: |
        An abstract representation of an object that is externally consumable via an API endpoint.
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.MetadataAbstractModel'
      - type: object
        properties:
          extId:
            type: string
            description: An identifier for the object that is suitable for external
              consumption.
          name:
            type: string
            description: |
              The tenant to which this object instance belongs.  Every Nutanix object belongs to a tenant. Once an object is created its tenancy cannot be changed.
          description:
            type: string
            description: |
              The tenant to which this object instance belongs.  Every Nutanix object belongs to a tenant. Once an object is created its tenancy cannot be changed.
          displayName:
            type: string
    common.unversioned.a1.data.types.MetadataAbstractModel:
      description: |
        An abstract representation of an object that is itself not consumable via an external API endpoint but provides metadata information in the form of HATEOAS links to the consumer.
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.AbstractModel'
      - type: object
        properties:
          links:
            type: array
            description: The HATEOAS links for the Vm API.  Minimally contains the
              self link
            items:
              $ref: '#/components/schemas/common.v5.r0.a1.response.types.ApiLink'
    common.unversioned.a1.data.types.AbstractModel:
      type: object
      properties:
        objectType:
          type: string
          description: A fully qualified name of the object represented by this entity
          readOnly: true
        tenantId:
          type: string
          description: |
            The tenant to which this object instance belongs.  Every Nutanix object belongs to a tenant. Once an object is created its tenancy cannot be changed.
          readOnly: true
    common.unversioned.a1.data.types.BaseEnum:
      type: string
      enum:
      - $UNKNOWN
    common.v5.r0.a1.response.types.ApiResponseMetadata:
      description: Metadata associated with API responses
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.MetadataAbstractModel'
      - type: object
        properties:
          totalCount:
            type: integer
            description: Represents the total count of the results available for this
              entity (if applicable).
            format: int64
    common.v5.r0.a1.response.types.ApiLink:
      allOf:
      - $ref: '#/components/schemas/common.unversioned.a1.data.types.AbstractModel'
      - type: object
        properties:
          href:
            type: string
            description: The URL that points to the relationship
          rel:
            type: string
            description: The name of the relationship
        description: HATEOAS links for the request.  For paginated requests includes
          prev/next/first and last links
