components:
  schemas:
     FileServer:
        allOf:
        - $ref: "ModelRef({/namespaces/common/unversioned/modules/data.types/alpha/models/ExternalizableAbstractModel})"
        - type: "object"
          properties:
            config:
              type: "object"
              $ref: "ModelRef({./FileServerConfig})"

     Network:
        title: "FileServer Config."
        description: "FileServer config."
        allOf:
        - $ref: "ModelRef({/namespaces/common/unversioned/modules/data.types/alpha/models/AbstractModel})"
        - type: "object"
          properties:
            uuid:
              type: "string"
              description: "Uuid of the network."
            name:
              type: "string"
              description: "Name of the network."
            networkAddress:
              type: "string"
              description: "NetworkAddress of the network."
            internalVirtualNetworkUuid:
              type: "string"
              description: "Uuid of the internal network."
            externalVirtualNetworkUuid:
              type: "string"
              description: "Uuid of the external network."
            isInternalNetwork:
              type: "boolean"
              description: "Uuid of the external network."
            subnetMask:
              type: "string"
              description: "Subnetmask of the network."
            defaultGateway:
              type: "string"
              description: "Default Gateway of the network."

     FileServerConfig:
        title: "FileServer Config."
        description: "FileServer config."
        allOf:
        - $ref: "ModelRef({/namespaces/common/unversioned/modules/data.types/alpha/models/AbstractModel})"
        - type: "object"
          properties:
            uuid:
              type: "string"
              description: "Uuid of the file server."
            name:
              type: "string"
              description: "Name of the file server."
            description:
              type: "string"
              description: "Description of the file server."
            dnsDomainNme:
              type: "string"
              description: "Dns domain name of the file server."
            continerUuid:
              type: "string"
              description: "Container uuid associated with file server."
            dnsServerIpAddresses:
              type: "array"
              description: "Dns server ip addresses."
              items:
                type: string
            ntpServers:
              type: "array"
              description: "ntp server ip addresses."
              items:
                type: string
            internalVirtualNetworkUuid:
              type: "string"
              description: "ntp server ip addresses."
            externalVirtualNetworkUuids:
              type: "array"
              description: "External network uuids."
              items:
                type: string
            internalNetwork:
              type: "object"
              $ref: "ModelRef({./Network})"
            externalNetworks:
              type: "array"
              items:
                type: "object"
                $ref: "ModelRef({./Network})"
            numShares:
              type: integer
              description: "Num of shares associated with the file server"
            numHomeShares:
              type: integer
              description: "Num of home shares associated with file server."
            numNestedShares:
              type: integer
              description: "Num of nested shares associated with file server."
            externalIpAddresses:
              type: array
              description: "External ip addresses"
              items:
                type: string
            version:
              type: string
              description: "version of file server"
            upgrdeInProgress:
              type: boolean
              description: "Upgrade in progress flag"
            protectedDomainState:
              type: boolean
              description: "Protection domain Status"
            pdStatus:
              type: boolean
              description: "Pd Status"
            protectionDomainName:
              type: string
              description: "protectionDomainName"





