name: Promote to LKG

on: push
  #schedule:
  #- cron:  '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Checkout Github Actions
        uses: actions/checkout@v2
        with:
          repository: nutanix-core/ntnx-api-release-engineering
          ref: v0
          token: ${{ secrets.MY_TOKEN }}
          path: .github/actions/lkg
      - name: Run LKG Action
        uses: ./.github/actions/lkg
         
      # merge LCC tagged commit from develop branch
      - name: Promote and merge
        run: |
          cd $GITHUB_WORKSPACE
          export GITHUB_OAUTH_TOKEN=${{ secrets.CANGIT_TOKEN }}
          export SERVICE_NAME=${GITHUB_REPOSITORY}
          export DEVELOP_BRANCH='develop'
          export GITHUB_ACTOR=${{ github.actor }}
          scripts/merge.sh 
