name: Promote to LKG

on:
  schedule:
  - cron:  '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master

    - uses: nutanix-core/ntnx-api-release-engineering@v0
      with:
        github_oauth_token:${{ secrets.GIT_TOKEN }}
         
    # merge LCC tagged commit from develop branch
    - name: Promote and merge
      run: |
        cd $GITHUB_WORKSPACE
        export GITHUB_OAUTH_TOKEN=${{ secrets.CANGIT_TOKEN }}
        export SERVICE_NAME=${GITHUB_REPOSITORY}
        export DEVELOP_BRANCH='develop'
        export GITHUB_ACTOR=${{ github.actor }}
        scripts/merge.sh 
