name: Promote to LKG

on: push
  #schedule:
  #- cron:  '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository under $GITHUB_WORKSPACE in docker container
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      # Check out Github Action to merge and promote to LKG under $GITHUB_WORKSPACE/.github/actions/lkg
      # This is because github actions can not be pulled directly from private repository,
      # even though it is under same org
      - name: Checkout Github Actions
        uses: actions/checkout@v2
        with:
          repository: nutanix-core/ntnx-api-release-engineering
          ref: v0
          token: ${{ secrets.MY_TOKEN }}
          path: .github/actions/lkg

      # Run LKG action. 
      # Note: 'uses' field can not have environment variable (github action does not allow variable in 'uses' field)
      - name: Run LKG Action
        uses: ./.github/actions/lkg
        with:
          # needed for github API call 
          github_oauth_token: ${{ secrets.CANGIT_TOKEN }}
          # branch to check out
          develop_branch:     'develop'
          # needed for git checkout
          github_actor:       ${{ github.actor }}
